name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt-get update
          sudo apt-get -y install libbrotli-dev
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.1

      - name: Build
        run: GOEXPERIMENT=arenas go build -v ./...

      - name: Test
        run: GOEXPERIMENT=arenas go test -v -race ./...

      - name: Bench Concurrent
        run: GOEXPERIMENT=arenas go test -cpu=1,2,4,8 -bench=BenchmarkSkiplist -run=XXX ./...
