name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt-get update
          sudo apt-get -y install libbrotli-dev
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Bench Race
        run: go test -race -cpu=2 -bench=BenchmarkConcurrent -run=XXX ./internal/cache/sorted/treemap/...

      - name: Bench Concurrent
        run: go test -cpu=1,2,4,8 -bench=BenchmarkConcurrent -run=XXX ./...
