# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt-get update
          sudo apt-get -y install libbrotli-dev
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Bench Concurrent
        run: go test -cpu=1,2,4,8 -bench=BenchmarkConcurrent -run=XXX ./...
